// <auto-generated />
namespace ERP.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HR_CNIC_Repo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HR_CNIC_Repo));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300739417_HR_CNIC_Repo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
