// <auto-generated />
namespace ERP.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HR_Task_TablesFurther : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HR_Task_TablesFurther));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161327367_HR_Task_TablesFurther"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
