// <auto-generated />
namespace ERP.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class domesticPaymentAddOnsAddittion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(domesticPaymentAddOnsAddittion));
        
        string IMigrationMetadata.Id
        {
            get { return "201908190834259_domesticPaymentAddOnsAddittion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
