// <auto-generated />
namespace ERP.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FabExport_detail_merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FabExport_detail_merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201912061108527_FabExport_detail_merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
