//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_financial_trans
    {
        public string VKey { get; set; }
        public int VoucherNo { get; set; }
        public decimal Credit { get; set; }
        public decimal Debit { get; set; }
        public Nullable<int> FinParty_Id { get; set; }
        public int DeptId { get; set; }
        public string Title { get; set; }
        public int EmpId { get; set; }
        public string Employee { get; set; }
        public string Location { get; set; }
        public int LocId { get; set; }
        public string City { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string GlTitle { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string Detail { get; set; }
        public string FescalMonth { get; set; }
        public string Vtype { get; set; }
        public string L5Code { get; set; }
        public string L1Code { get; set; }
        public string L1Title { get; set; }
        public string L2Code { get; set; }
        public string L2Title { get; set; }
        public string L3Code { get; set; }
        public string L3Title { get; set; }
        public string L4Code { get; set; }
        public string L4Title { get; set; }
    }
}
