//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLCOAView> ALLCOAViews { get; set; }
        public virtual DbSet<view_financial_trans> view_financial_trans { get; set; }
        public virtual DbSet<view_financial_trial_ledger> view_financial_trial_ledger { get; set; }
        public virtual DbSet<VIEW_FinLedger> VIEW_FinLedger { get; set; }
        public virtual DbSet<VW_COA> VW_COA { get; set; }
        public virtual DbSet<view_domestic_inquiry> view_domestic_inquiry { get; set; }
        public virtual DbSet<view_domestic_disp_return_Summary> view_domestic_disp_return_Summary { get; set; }
        public virtual DbSet<view_IndDomestic_Inquiry_Offers> view_IndDomestic_Inquiry_Offers { get; set; }
        public virtual DbSet<view_IndDomestic_inquiry_sheet> view_IndDomestic_inquiry_sheet { get; set; }
        public virtual DbSet<view_sale_register> view_sale_register { get; set; }
        public virtual DbSet<view_IndDomestic_detail> view_IndDomestic_detail { get; set; }
    
        public virtual ObjectResult<SP_DEBIT_CRIDET_Result> SP_DEBIT_CRIDET(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DEBIT_CRIDET_Result>("SP_DEBIT_CRIDET", fromParameter, toParameter);
        }
    
        public virtual ObjectResult<SP_GETRECORD_Result> SP_GETRECORD(Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("From", from) :
                new ObjectParameter("From", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETRECORD_Result>("SP_GETRECORD", fromParameter, toParameter);
        }
    
        public virtual ObjectResult<SP_Year_Accounts_Analysis_Result> SP_Year_Accounts_Analysis(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Year_Accounts_Analysis_Result>("SP_Year_Accounts_Analysis", dateParameter);
        }
    }
}
