//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_IndDomestic_Inquiry_Offers
    {
        public int indentId { get; set; }
        public string LocalContractNo { get; set; }
        public System.DateTime IndentDate { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public int Revision { get; set; }
        public int InquiryId { get; set; }
        public string InquiryKey { get; set; }
        public System.DateTime InquiryDate { get; set; }
        public int id { get; set; }
        public string Department { get; set; }
        public int CommodityId { get; set; }
        public string Commodity { get; set; }
        public decimal Quantity { get; set; }
        public string UOS { get; set; }
        public Nullable<decimal> DispQuantity { get; set; }
        public Nullable<decimal> ReturnQuantity { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public string PaymentTerms { get; set; }
        public string ComodityType { get; set; }
        public string UOR { get; set; }
        public Nullable<System.DateTime> InquiryClosedDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Delivery { get; set; }
        public string InquiryStatus { get; set; }
        public string IsClosed { get; set; }
        public string Title { get; set; }
        public int DepartmentID { get; set; }
        public int SellectId { get; set; }
        public string seller { get; set; }
        public string BuyerId { get; set; }
        public string CustomerAsBuyer { get; set; }
        public bool IndentStatus { get; set; }
        public bool indentClosed { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string Rivew { get; set; }
        public Nullable<bool> ReviewStatus { get; set; }
        public string OfferedBy { get; set; }
        public Nullable<decimal> OfferedRate { get; set; }
        public Nullable<System.DateTime> OfferMadeOn { get; set; }
        public string OfferRemarks { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public string OfferPaymentTerms { get; set; }
    }
}
