//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_sale_register
    {
        public string IndentKey { get; set; }
        public System.DateTime IndentDate { get; set; }
        public int CustomerId { get; set; }
        public int CustomerIDasSeller { get; set; }
        public string SellerName { get; set; }
        public int CustomerIDasBuyer { get; set; }
        public string BuyerName { get; set; }
        public int CustomerIDasLocalAgent { get; set; }
        public System.DateTime OfferDate { get; set; }
        public System.DateTime confirmDate { get; set; }
        public int CommodityTypeId { get; set; }
        public string CommodityType { get; set; }
        public int InquiryId { get; set; }
        public string InquiryKey { get; set; }
        public int DepartmentID { get; set; }
        public int PaymenTermsId { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public string QuantityVariance { get; set; }
        public decimal TotalValue { get; set; }
        public decimal TotalValueOnCommRate { get; set; }
        public string PackingRemarks { get; set; }
        public string DeliveryRemarks { get; set; }
        public string DeliveryRemarksBuyer { get; set; }
        public string GeneralRemarks { get; set; }
        public string SpecialConditions { get; set; }
        public string PriceTerms { get; set; }
        public string Destination { get; set; }
        public string ClosingRemaks { get; set; }
        public System.DateTime closedDate { get; set; }
        public decimal ExecutedTotalValue { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime LastApprovedOn { get; set; }
        public int ApprovedBy { get; set; }
        public int MarketedBy { get; set; }
        public bool IsSubmitForApproval { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IndentStatus { get; set; }
        public bool isClosed { get; set; }
        public bool IsUpdated { get; set; }
        public bool isCancelled { get; set; }
        public bool isShipments { get; set; }
        public bool isInvoiced { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDueDate { get; set; }
        public int CommodityId { get; set; }
        public string Commidity { get; set; }
        public string CommoditySpecification { get; set; }
        public int UosID { get; set; }
        public string UOS { get; set; }
        public string UOM { get; set; }
        public string UOR { get; set; }
        public decimal Factor { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal CommRate { get; set; }
        public decimal QuantityReq { get; set; }
        public decimal ProductTotalAmount { get; set; }
        public decimal ProductCommValue { get; set; }
        public decimal ExecutedQuantity { get; set; }
        public decimal ExecutedValue { get; set; }
        public decimal CalculatedCommissionValue { get; set; }
    }
}
