//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_domestic_disp_return_Summary
    {
        public int IndentId { get; set; }
        public int CommodityId { get; set; }
        public Nullable<decimal> DispQuantity { get; set; }
        public Nullable<decimal> ReturnQuantity { get; set; }
    }
}
