//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_financial_trial_ledger
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string VKey { get; set; }
        public string GlCode { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public System.DateTime ClearingDate { get; set; }
        public string ChequeNo { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public int UserId { get; set; }
        public string L1Code { get; set; }
        public string l1Title { get; set; }
        public string L2Code { get; set; }
        public string l2Title { get; set; }
        public string L3Code { get; set; }
        public string L3Title { get; set; }
        public string L4Code { get; set; }
        public string l4Title { get; set; }
        public string Type { get; set; }
    }
}
