//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIGOR.ViewsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COA
    {
        public int LevelOfAccount { get; set; }
        public string ParentAccount { get; set; }
        public string AccountCode { get; set; }
        public string AccountTitle { get; set; }
    }
}
